var D=[
// {id:"anime",n:"Anime",img:"designs/thumb/anime.webp"},
// {id:"cars-and-bikes",n:"Cars And Bikes",img:"designs/thumb/cars-and-bikes.webp"},
// {id:"revolution",n:"Revolution",img:"designs/thumb/revolution.webp"},
// {id:"super-hero",n:"Super Hero",img:"designs/thumb/super-hero.webp"},
{id:"zodiac",n:"Zodiac",img:"designs/blaze-marble.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/blaze-sunset.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/cinder-geo.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/coral-geo-6.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/ember-stripes-7.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/glacier-geo-6.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/noir-stripes-3.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/ember-contour-8.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/dusk-dots-2.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/blaze-marble-2.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/ember-contour-3.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/slate-waves-4.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/forest-peaks-7.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/teal-peaks.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/teal-stars-2.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/violet-marble.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/noir-contour.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/lagoon-sunset-7.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/lagoon-sunset-4.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/lagoon-marble-4.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/lagoon-marble-2.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/lagoon-marble.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/forest-stars.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/glacier-terrazzo-2.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/glacier-terrazzo-3.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/neon-contour-2.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/neon-stripes-3.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/ocean-dots.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/cinder-terrazzo-2.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/ocean-dots-3.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/ocean-waves-2.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/ocean-waves-3.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/orchid-stars-6.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/plum-contour-6.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/plum-stripes-3.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/sage-geo-5.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/sage-terrazzo-2.jpg"},
// {id:"zodiac",n:"Zodiac",img:"designs/slate-dots-3.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/slate-waves-4.jpg"},
// {id:"zodiac",n:"Zodiac",img:"designs/slate-waves-7.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/001.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/002.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/003.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/004.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/005.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/006.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/007.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/008.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/009.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0011.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0012.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0013.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0014.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0015.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0016.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0017.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0018.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0019.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0020.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0021.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0022.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0023.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0024.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0025.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0026.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0027.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0028.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0029.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0030.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0031.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0032.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0033.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0034.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0035.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0036.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0037.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0038.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0039.jpg"},
// {id:"zodiac",n:"Zodiac",img:"designs/anime/0040.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0041.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0042.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0043.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0044.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0045.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0046.jpg"},
// {id:"zodiac",n:"Zodiac",img:"designs/anime/0047.jpg"},
// {id:"zodiac",n:"Zodiac",img:"designs/anime/0048.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0049.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0050.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0051.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0052.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0053.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0054.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0055.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0056.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0057.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0058.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0059.jpg"},
{id:"zodiac",n:"Zodiac",img:"designs/anime/0060.jpg"},






];
